ALTER TABLE api_keys ADD COLUMN IF NOT EXISTS role TEXT NOT NULL DEFAULT 'service_role';
ALTER TABLE api_keys ADD COLUMN IF NOT EXISTS principal_type TEXT NOT NULL DEFAULT 'Service';
ALTER TABLE api_keys ADD COLUMN IF NOT EXISTS key_prefix TEXT;
